// Traductions des cuisines (clé = anglais, valeur = français)
export const CUISINE_LABELS_FR = {
  African: "Africaine",
  Asian: "Asiatique",
  American: "Américaine",
  British: "Britannique",
  Cajun: "Cajun",
  Caribbean: "Caribéenne",
  Chinese: "Chinoise",
  "Eastern European": "Européenne de l'Est",
  European: "Européenne",
  French: "Française",
  German: "Allemande",
  Greek: "Grecque",
  Indian: "Indienne",
  Irish: "Irlandaise",
  Italian: "Italienne",
  Japanese: "Japonaise",
  Korean: "Coréenne",
  "Latin American": "Latino-américaine",
  Mediterranean: "Méditerranéenne",
  Mexican: "Mexicaine",
  "Middle Eastern": "Moyen-Orientale",
  Nordic: "Nordique",
  Southern: "Du Sud",
  Spanish: "Espagnole",
  Thai: "Thaïlandaise",
  Vietnamese: "Vietnamienne",
};

// Traductions des types de repas (clé = anglais, valeur = français)
export const MEAL_TYPE_LABELS_FR = {
  "main course": "Plat principal",
  "side dish": "Accompagnement",
  dessert: "Dessert",
  appetizer: "Apéritif",
  salad: "Salade",
  bread: "Pain",
  breakfast: "Petit-déjeuner",
  soup: "Soupe",
  beverage: "Boisson",
  sauce: "Sauce",
  marinade: "Marinade",
  fingerfood: "Fingerfood",
  snack: "Snack",
  drink: "Boisson",
};