// Groupes d'ingrédients en anglais (pour Spoonacular)
export const INGREDIENT_GROUPS = {
  meats_and_poultry: [
    "chicken",
    "beef",
    "turkey",
    "veal",
    "lamb",
    "duck",
    "rabbit",
  ],
  fish_and_seafood: [
    "tuna",
    "shrimp",
    "salmon",
    "sardine",
    "hake",
    "cod",
    "tilapia",
    "monkfish",
  ],
  dairy_and_eggs: ["egg", "milk", "cheese", "cream", "parmesan"],
  cereals_and_starches: [
    "rice",
    "pasta",
    "bread",
    "bulgur",
    "quinoa",
    "semolina",
    "polenta",
    "buckwheat",
    "rye",
    "barley",
    "spelt",
  ],
  root_vegetables: [
    "potato",
    "sweet potato",
    "beetroot",
    "turnip",
    "radish",
    "carrot",
  ],
  leafy_and_cruciferous_vegetables: [
    "spinach",
    "arugula",
    "parsley",
    "watercress",
    "lettuce",
    "endive",
    "cabbage",
    "chard",
    "basil",
    "coriander",
    "mint",
    "rosemary",
    "leek",
    "cauliflower",
    "broccoli",
    "zucchini",
    "eggplant",
    "squash",
    "pattypan squash",
    "onion",
    "garlic",
    "pepper",
  ],
  fruit_vegetables: ["tomato", "avocado", "corn", "capers", "lemon"],
  nuts_and_seeds: ["walnut", "almond", "hazelnut", "coconut", "sesame"],
  legumes: [
    "lentil",
    "chickpea",
    "bean",
    "soy",
    "tofu",
    "tempeh",
    "seitan",
    "miso",
  ],
  fresh_fruits: [
    "apple",
    "banana",
    "orange",
    "strawberry",
    "blueberry",
    "pineapple",
    "pear",
    "kiwi",
    "fig",
    "date",
    "apricot",
  ],
  others: ["pesto", "honey", "mustard"],
};

// (Optionnel si tu veux aussi l'anglais pour fallback)
export const INGREDIENT_GROUP_LABELS = {
  meats_and_poultry: "Meats & Poultry",
  fish_and_seafood: "Fish & Seafood",
  dairy_and_eggs: "Dairy & Eggs",
  cereals_and_starches: "Cereals & Starches",
  root_vegetables: "Root Vegetables",
  leafy_and_cruciferous_vegetables: "Leafy & Cruciferous Vegetables",
  fruit_vegetables: "Fruit Vegetables",
  nuts_and_seeds: "Nuts & Seeds",
  legumes: "Legumes",
  fresh_fruits: "Fresh Fruits",
  others: "Others",
};

export const CUISINES = [
  "African",
  "Asian",
  "American",
  "British",
  "Cajun",
  "Caribbean",
  "Chinese",
  "Eastern European",
  "European",
  "French",
  "German",
  "Greek",
  "Indian",
  "Irish",
  "Italian",
  "Japanese",
  "Korean",
  "Latin American",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Nordic",
  "Southern",
  "Spanish",
  "Thai",
  "Vietnamese",
];

export const MEAL_TYPES = [
  "main course",
  "side dish",
  "dessert",
  "appetizer",
  "salad",
  "bread",
  "breakfast",
  "soup",
  "beverage",
  "sauce",
  "marinade",
  "fingerfood",
  "snack",
  "drink",
];